### ISSUE TITLE
Endpoint "/pets" não retorna 404 quando não há dados em uma consulta

### ISSUE THREAD

**Issue by genesluna** [hywenklis/buddy-backend#47]
Ao fazer uma consulta que deveria retornar um status code 404, o endpoint devolve uma resposta com com os objetos _links e page.

### Comportamento esperado
Retornar um status code 404

### Passos para reproduzir
Chamar o endpoint com uma busca que não renorna resultados, como a seguir: 
[https://buddy.propresto.app/api/v1/pets?ageRange=10%2B+anos&page=0&size=8](https://buddy.propresto.app/api/v1/pets?ageRange=10%2B+anos&page=0&size=8)

### Contexto
Preciso tratar os status codes no frontend para poder mostrar uma resposta adequada ao usuário.

**Comment by hywenklis** [comment]
Olá @genesluna, tudo bem?

Entendi seu ponto, mas gostaria de explicar por que a prática de utilizar o status 200 com um objeto vazio, em vez de 404, pode ser mais benéfica.

Podemos ter ganhos em alguns pontos:

1. **Consistência de Resposta:**
   - Manter um status code 200 para consultas de busca é consistente, independentemente de haver resultados ou não. Isso evita que os clientes da API precisem tratar diferentes códigos de status para a mesma operação de busca.

2. **Distinção entre Recurso e Consulta:**
   - Um status code 404 é usado para indicar que um recurso específico não foi encontrado. No caso de uma consulta de busca, a ausência de resultados não significa que o endpoint ou o recurso não existe, mas apenas que não há correspondências para os critérios de busca fornecidos.

3. **Semântica da Resposta:**
   - Retornar um status code 200 com um corpo de resposta vazio ou uma estrutura adequada (por exemplo, `{ "results": [], "total": 0 }`) comunica claramente que a operação foi bem-sucedida, mas não houve resultados. Isso é mais claro do que um 404, que poderia ser interpretado como um erro ou um problema na API.

O que você acha dessa abordagem? Ela poderia simplificar o tratamento de respostas e melhorar a clareza da API. Estou aberto a ouvir suas opiniões e sugestões sobre isso.

**Comment by genesluna** [comment]
Eu concordo com tudo que você disse e sei que esse é um dos padrões adotados. É que sempre adotei o padrão de mandar e receber um 404 junto com o corpo de resposta vazio:

```json
HTTP/1.1 404 Not Found
Content-Type: application/json

{
    "_links": {
        "self": {
            "href": "https://buddy.propresto.app/api/v1/pets?ageRange=10%2B+anos&page=0&size=8"
        }
    },
    "page": {
        "size": 8,
        "totalElements": 0,
        "totalPages": 0,
        "number": 0
      }
}
```

Dessa forma o servidor comunica claramente que a operação foi processada, mas também explicita que nem tudo aconteceu conforme esperado, já que o 200 quer dizer que a requisição obteve sucesso, o que é uma meia verdade já que o que eu procurava não foi encontrado. Isso facilita do lado do cliente, pois quando há um 404, o cliente já me comunica que as coisas não aconteceram devidamente. Já com o 200, tenho que criar uma lógica para checar se o número de páginas é zero. 

Mas eu não tenho problemas em usar o padrão que você adotou. :blush:
